# Generated by Django 4.2.4 on 2023-08-13 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.IntegerField(default=123),
            preserve_default=False,
        ),
    ]
