# Generated by Django 4.2.4 on 2023-08-28 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='заголовок')),
                ('slug', models.CharField(max_length=200, verbose_name='ЧПУ')),
                ('content', models.TextField(verbose_name='Содержимое')),
                ('preview', models.ImageField(blank=True, null=True, upload_to='blogs/', verbose_name='превью')),
                ('created_date', models.DateTimeField(verbose_name='дата создания')),
                ('is_public', models.BooleanField(verbose_name='опубликовано или нет')),
                ('views_count', models.IntegerField(verbose_name='количество просмотров')),
            ],
        ),
    ]
