# Generated by Django 4.2.4 on 2023-08-28 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='is_public',
            field=models.BooleanField(default=True, verbose_name='опубликовано или нет'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='views_count',
            field=models.IntegerField(default=0, verbose_name='количество просмотров'),
        ),
    ]
